
export const ADD_USER = "ADD_USER";
export const UPDATE_USER = "UPDATE_USER";
export const REMOVE_USER = "REMOVE_USER";
export const ADD_PROPERTY = "ADD_PROPERTY";
export const REMOVE_PROPERTY = "REMOVE_PROPERTY";
export const UPDATE_PROPERTY = "UPDATE_PROPERTY";
export const UPDATE_PROPERTIES = "UPDATE_PROPERTIES";
export const QUERY_PROPERTIES = "QUERY_PROPERTIES";
export const TOGGLE_UPDATE_FORM = "TOGGLE_UPDATE_FORM"



